
# Generated by Django 5.2.11 on 2026-04-29 07:41

# Generated by Django 5.2.11 on 2026-03-30 11:16
# Generated by Django 5.2 on 2026-04-10 08:58


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom de la salle')),
                ('capacite', models.IntegerField(default=30)),
                
                ('equipements', models.TextField(help_text='Videoprojecteur, Sonorisation, etc.')),
                ('est_disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indisponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_indisponible', models.CharField(choices=[('JURY', 'Membre du jury'), ('SALLE', 'Salle')], max_length=10)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('raison', models.CharField(blank=True, max_length=255, null=True)),
                ('utilisateur', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['EXAMINER', 'PRESIDENT_JURY', 'DIRECTOR']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilites', to=settings.AUTH_USER_MODEL)),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilites', to='scheduling.salle')),
            ],
            options={
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                # ('date_soutenance', models.DateTimeField()),
                # ('session', models.CharField(choices=[('1', 'Session 1'), ('2', 'Session 2'), ('3', 'Session 3'), ('4', 'Session 4'), ('5', 'Session 5'), ('6', 'Session 6'), ('7', 'Session 7'), ('8', 'Session 8'), ('9', 'Session 9'), ('10', 'Session 10'), ('11', 'Session 11'), ('12', 'Session 12')], max_length=2)),
                # ('pre_soutenance_validee', models.BooleanField(default=False)),
                # ('est_cloturee', models.BooleanField(default=False)),
                # ('lien_meet', models.URLField(blank=True, null=True)),

                ('date_soutenance', models.DateTimeField(verbose_name='Date et Heure')),
                ('session', models.CharField(choices=[('1', 'Session 1'), ('2', 'Session 2'), ('3', 'Session 3'), ('4', 'Session 4'), ('5', 'Session 5'), ('6', 'Session 6'), ('7', 'Session 7'), ('8', 'Session 8'), ('9', 'Session 9'), ('10', 'Session 10'), ('11', 'Session 11'), ('12', 'Session 12')], max_length=2, verbose_name='Session Mensuelle')),
                ('pre_soutenance_validee', models.BooleanField(default=False, verbose_name='Pré-soutenance effectuée')),
                ('est_cloturee', models.BooleanField(default=False)),
                ('lien_meet', models.URLField(blank=True, help_text="En cas d'absence physique (Règle Meet)", null=True)),
                #('pre_soutenance_validee', models.BooleanField(default=False, verbose_name='Pre-soutenance effectuee')),
                #('est_cloturee', models.BooleanField(default=False)),
                #('lien_meet', models.URLField(blank=True, help_text="En cas d'absence physique (Regle Meet)", null=True)),

                ('directeur_memoire', models.ForeignKey(limit_choices_to={'role__in': ['INTERNAL_TRAINER', 'EXTERNAL_TRAINER']}, on_delete=django.db.models.deletion.PROTECT, related_name='directions', to=settings.AUTH_USER_MODEL)),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soutenance', to='academic.studentprofile')),
                ('examinateur', models.ForeignKey(limit_choices_to={'role': 'EXAMINER'}, on_delete=django.db.models.deletion.PROTECT, related_name='examinations', to=settings.AUTH_USER_MODEL)),
                ('president', models.ForeignKey(limit_choices_to={'role': 'PRESIDENT_JURY'}, on_delete=django.db.models.deletion.PROTECT, related_name='presidences', to=settings.AUTH_USER_MODEL)),
                ('salle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.salle')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.themesoutenance')),
            ],
            options={
                'verbose_name': 'Soutenance',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_presentation', models.FloatField(default=0)),
                ('note_maitrise', models.FloatField(default=0)),
                ('note_memoire', models.FloatField(default=0)),
                ('note_reponses', models.FloatField(default=0)),
                ('remarques_jury', models.TextField(blank=True)),
                ('mention', models.CharField(blank=True, max_length=50)),
                ('pv_genere', models.FileField(blank=True, null=True, upload_to='pvs/')),
                ('est_signe_par_tous', models.BooleanField(default=False)),
                ('soutenance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultat', to='scheduling.soutenance')),
            ],
        ),
        migrations.AddConstraint(
            model_name='soutenance',
            constraint=models.UniqueConstraint(fields=('salle', 'date_soutenance'), name='unique_salle_par_date'),
        ),
    ]
