# Generated by Django 5.2 on 2026-05-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='soutenance',
            name='unique_salle_par_date',
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='lien_meet',
            field=models.URLField(blank=True, help_text="En cas d'absence physique (Regle Meet)", null=True),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='pre_soutenance_validee',
            field=models.BooleanField(default=False, verbose_name='Pre-soutenance effectuee'),
        ),
        migrations.AlterUniqueTogether(
            name='soutenance',
            unique_together={('salle', 'date_soutenance')},
        ),
    ]
