
# Generated by Django 5.2.11 on 2026-04-29 07:41

# Generated by Django 5.2.11 on 2026-03-30 11:16
# Generated by Django 5.2 on 2026-04-10 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bordereau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bordereau', models.CharField(max_length=100, unique=True, verbose_name='N° du Bordereau')),
                ('banque', models.CharField(default='ECOBANK', help_text='Banque de dépôt', max_length=100)),
                ('montant', models.IntegerField(choices=[(100000, '100.000 F (Licence)'), (150000, '150.000 F (Master)')])),
                ('image_bordereau', models.ImageField(upload_to='paiements/bordereaux/', verbose_name='Scan du bordereau')),
                ('est_valide', models.BooleanField(default=False, verbose_name='Paiement Confirmé')),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='academic.studentprofile')),
                ('valide_par', models.ForeignKey(blank=True, limit_choices_to={'role': 'SERVICE_RECOUVREMENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
    ]
