# Generated by Django 5.2.11 on 2026-04-29 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la filiere')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('niveau', models.CharField(choices=[('LICENCE', 'Licence'), ('MASTER', 'Master')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeSoutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Thème proposé')),
                ('description', models.TextField(verbose_name='Problématique et Objectifs')),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('VALIDATED', 'Valide (OK)'), ('REJECTED', 'Rejete/A modifier')], default='PENDING', max_length=20)),
                ('remarques_examinateur', models.TextField(blank=True, null=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('verifie_plagiat', models.BooleanField(default=False, verbose_name='Vérification anti-plagiat effectuée')),
                ('verifie_ia', models.BooleanField(default=False, verbose_name='Vérification anti-IA effectuée')),
                ('date_verification', models.DateTimeField(blank=True, null=True, verbose_name='Date de vérification')),
                ('rapport_verification', models.FileField(blank=True, null=True, upload_to='verifications/%Y/%m/')),
                ('commentaire_verification', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniteEnseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('code_ue', models.CharField(max_length=20, unique=True)),
                ('credits_ects', models.IntegerField(default=6)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('has_paid_fees', models.BooleanField(default=False, verbose_name='Frais de soutenance payes')),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.filiere')),
            ],
        ),
    ]
