# Generated by Django 5.2.11 on 2026-04-29 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='themesoutenance',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.studentprofile'),
        ),
        migrations.AddField(
            model_name='themesoutenance',
            name='examinateur_assigne',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'EXAMINER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes_to_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='themesoutenance',
            name='verifie_par',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['CHEF_SERVICE_EXAM', 'ADMIN_ACADEMIC']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_effectuees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uniteenseignement',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ue_list', to='academic.filiere'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='ue_validees',
            field=models.ManyToManyField(blank=True, related_name='students_who_passed', to='academic.uniteenseignement'),
        ),
    ]
