
# Generated by Django 5.2.11 on 2026-04-29 07:41

# Generated by Django 5.2.11 on 2026-03-30 11:16
# Generated by Django 5.2 on 2026-04-10 08:58


import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('DEPOT', 'Attestation de Dépôt'), ('RECURRENCE', 'Attestation de Réussite')], max_length=20)),
                ('fichier_genere', models.FileField(upload_to='attestations/')),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('UPLOAD', 'Upload'), ('VALIDATE', 'Validation'), ('BLOCK', 'Blocage')], max_length=20)),
                ('objet_type', models.CharField(max_length=100)),
                ('objet_id', models.IntegerField()),
                ('details', models.JSONField(default=dict)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_log_entry',
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='Memoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_final', models.CharField(max_length=255)),
                ('fichier_pdf', models.FileField(upload_to=documents.models.student_directory_path, verbose_name='Version PDF (Immuable)')),
                ('fichier_word', models.FileField(upload_to=documents.models.student_directory_path, verbose_name='Version Word (Anti-plagiat)')),
                ('support_presentation', models.FileField(blank=True, null=True, upload_to=documents.models.student_directory_path, verbose_name='Support PowerPoint')),
                ('est_valide_par_directeur', models.BooleanField(default=False, verbose_name='Quitus du Directeur')),
                ('verifie_anti_plagiat', models.BooleanField(default=False, verbose_name='Vérification Plagiat/IA')),
                ('score_similarite', models.FloatField(default=0.0, help_text='Pourcentage de similarité détecté')),
                ('nb_pages', models.IntegerField(help_text='Licence: max 90, Master: 100-120', verbose_name='Nombre de pages')),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_memoire', to='academic.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProcesVerbal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_pv', models.FileField(blank=True, null=True, upload_to='pvs/%Y/%m/')),
                ('code_archive', models.CharField(max_length=50, unique=True, verbose_name="Code d'archivage bibliothèque")),
                ('signe_par_president', models.BooleanField(default=False)),
                ('signe_par_examinateur', models.BooleanField(default=False)),
                ('signe_par_directeur', models.BooleanField(default=False)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('soutenance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pv_officiel', to='scheduling.soutenance')),
            ],
            options={
                'verbose_name': 'Procès-Verbal',
                'verbose_name_plural': 'Procès-Verbaux',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('memoire', 'Mémoire'), ('pv', 'Procès-verbal'), ('attestation', 'Attestation')], max_length=20)),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('version', models.IntegerField(default=1)),
                ('est_valide', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='academic.studentprofile')),
            ],
            options={
                'ordering': ['-date_upload'],
                'unique_together': {('etudiant', 'type_document', 'version')},
            },
        ),
    ]
